name: X-Asena
on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: '16.x'
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests and generate coverage report
        run: |
          npm install jest
          npm install --save-dev jest-junit
          jest --coverage --coverageReporters=text-lcov | tee coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov
          env_vars: OS,NODE_VERSION
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
